{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onyx-stack.fullname" . }}-ingress-api
  annotations:
  {{- with .Values.ingress.api.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.api.host }}
      http:
        paths:
          - path: {{ .Values.ingress.api.path | default "/api(/|$)(.*)" }}
            pathType: {{ .Values.ingress.api.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "onyx-stack.fullname" . }}-api-service
                port:
                  number: {{ .Values.api.service.servicePort }}
  {{- if .Values.ingress.api.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.api.host }}
      secretName: {{ .Values.ingress.api.tlsSecretName }}
  {{- end }}
{{- end }}